learning_log/learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls',namespace = 'users')),
    path('', include('learning_logs.urls',namespace = 'learning_logs')),
]

learning_log/learning_logs/urls.py
#定义learning_logs的URL模式

from django.urls import path,re_path
from . import views
from .models import Topic
app_name = 'learning_logs'

urlpatterns = [
    #主页
    path('',views.index,name='index'),
    re_path(r'topics/$',views.topics,name='topics'),
    #特定主题
    re_path(r'topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    #添加新主题的网页
    re_path(r'new_topic/$',views.new_topic,name='new_topic'),
    #添加新blog
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    #用于编辑条目的页面
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    #删除blog
    re_path(r'^delete_entry/(?P<entry_id>\d+)$', views.delete_entry, name='delete_entry'),
    #删除主题
    re_path(r'^delete_topic/(?P<topic_id>\d+)$', views.delete_topic, name='delete_topic'),
]

learning_log/users/urls.py
#定义users的URL模式
from django.urls import path,re_path
from django.contrib.auth.views import LoginView
from . import views
app_name = 'users'

urlpatterns = [
    #登陆界面
    re_path(r'^login/$',LoginView.as_view(template_name = 'users/login.html'),name='login'),
    #注销
    re_path(r'^logout/$',views.logout_view,name='logout'),
    #注册页面
    re_path(r'^register/$',views.register,name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    #用户学习的主题
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    #某个主题的知识
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm): 
    class Meta: 
        model = Topic 
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry 
        fields = ['title','text']
        labels = {'title': '','text': ''}
        widgets = {'title': forms.Textarea(attrs={'cols': 80,'rows': 1}),
                    'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from enum import Flag
from typing import Any
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.http.response import Http404
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import render, get_object_or_404

from .forms import EntryForm, TopicForm
from .models import Entry, Topic


# Create your views here.
def index(request):
    #学习笔记的主页
    return render(request,'learning_logs/index.html')

@login_required #在展示topic前先运行装饰器
def topics(request):
    #显示所有的主题
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    #显示单个主题及其所有的条目
    topic = get_object_or_404(Topic, id=topic_id)
    #topic = Topic.objects.get(id=topic_id)
    #确认用户是否允许
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request): 
    #添加新主题
    if request.method != 'POST': # 未提交数据：创建一个新表单
        form = TopicForm()
    else:# POST提交的数据,对数据进行处理
        form = TopicForm(request.POST) 
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id): 
    #在特定的主题中添加新条目
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST': # 未提交数据,创建一个空表单
        form = EntryForm() 
    else:# POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request, entry_id):
    #编辑既有条目
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST': # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:# POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST) 
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    """ 删除既有条目 """
    entry = Entry.objects.get(id=entry_id)
    entry.delete()    
    # 显示当前Topic画面
    return topic(request, entry.topic.id)

@login_required
def delete_topic(request, topic_id):
    """ 删除既有条目 """
    topic = Topic.objects.get(id=topic_id)
    topic.delete()    
    # 显示当前Topics画面
    return topics(request)

learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    #注销用户
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request): 
    #注册新用户
    if request.method != 'POST': # 显示空的注册表单
        form = UserCreationForm()
    else:# 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save() # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>My Log</title>
        
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body> 
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container"> 
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" 
                    data-toggle="collapse" data-target="#navbar" 
                    aria-expanded="false" aria-controls="navbar"> 
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                        My Log</a>
                </div>
                    
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right"> 
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">log out</a></li>
                        {% else %} 
                            <li><a href="{% url 'users:register' %}">register</a></li>
                            <li><a href="{% url 'users:login' %}">log in</a></li> 
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse --> 
            </div>
        </nav>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div> 
            <div>
                {% block content %}{% endblock content %} 
            </div>
        </div> <!-- /container --> 
    </body> 
    
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p><h5>修改记录</h5></p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        <label>标 题</label>
        <textarea style="width:100%" name="title" class="form-control" maxlength="50" required="" id="id_title">{{entry.title}}</textarea>
        <label>正 文</label>
        <textarea style="width:100%; height:180px;" name="text" class="form-control" cols="80" rows="10" required="" id="id_text">{{entry.text}}</textarea><br>
    <button name="submit">保 存</button>
    </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %} 

{% block header %} 
    <div class='jumbotron'> 
        <h1>Track your Life.</h1> 
    </div> 
{% endblock header %} 

{% block content %} 
    <h2> 
        <a href="{% url 'users:register' %}">Register an account</a> 
        to make your own Log, and list the topics you're recording about. 
    </h2> 
    <h2>
        Whenever you have something new to record, 
        make a log summarizing what you've experienced. 
    </h2> 
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p><h4><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h4></p>

    <p><h5>添加新纪录</h5></p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        <label>标 题</label>
        <input type="title" class="form-control" name="title" id="id_title"><br>
        <label>正 文</label>
        <textarea style="width:100%; height:180px;" name="text" class="form-control" cols="80" rows="10" required="" id="id_text"></textarea><br>
    <button name="submit">添 加</button>
    </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %} 
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form"> 
        
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">保 存</button> 
        {% endbuttons %} 
    </form> 
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %} 
    <h2>{{ topic }}</h2> 
{% endblock header %} 

{% block content %} 
    <p>
        <a type="button" class="btn btn-primary"
        href="{% url 'learning_logs:new_entry' topic.id %}">添加新记录</a> 
    </p> 

    {% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                <p class="ellipsis">{{ entry.title }}</p>
                <h5>
                    <p align="right">{{ entry.date_added|date:'M d, Y H:i' }}</p>
                </h5>
                
                <small> 
                    <p align="right">
                        <a type="button" class="btn btn-primary" 
                        href="{% url 'learning_logs:edit_entry' entry.id %}">编 辑</a>
                        <a type="button" class="btn btn-danger" 
                        href="{% url 'learning_logs:delete_entry' entry.id %}">删 除</a>
                    </p>
                </small>
            </h3> 
        </div>
        
        <div class="panel-body"> 
            {{ entry.text|linebreaks }} 
        </div> 
    </div> <!-- panel --> 
    {% empty %} 
        <h3>此主题暂无记录，快来记录你的生活吧！</h3>
    {% endfor %} 
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %} 
    <h1>Topics</h1> 
{% endblock header %} 

{% block content %} 
    <ul>{% for topic in topics %} 
        <li> 
            <h3 class:"f"> 
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                <p align="right"><a type="button" class="btn btn-danger" 
                    href="{% url 'learning_logs:delete_topic' topic.id %}">删 除</a></p>
            </h3>
        </li> 
    {% empty %} 

        <li>No topics have been added yet.</li> 
        {% endfor %} 
    </ul>
    
        <h3>
            <a type="button" class="btn btn-primary"
            href="{% url 'learning_logs:new_topic' %}">添加新主题</a>
        </h3> 

{% endblock content %}

learning_log/users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %} 
    <h2>Log in to your account.</h2> 
{% endblock header %} 

{% block content %} 
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %} 
        {% bootstrap_form form %} 

        {% buttons %} 
            <button name="submit" class="btn btn-primary">登 录</button>
        {% endbuttons %} 
        
        <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" /> 
    </form> 
{% endblock content %}

learning_log/users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %} 

    <form method="post" action="{% url 'users:register' %}"> 
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" /> 
    </form>
    
{% endblock content %}